### ISSUE TITLE
Recover `timing` property on site resource

### ISSUE THREAD

**Issue by thoutenbos** [chef-cookbooks/chef_nginx#70]
Ever since the `site` resource was reimplemented in v4.0.0 the `timing` property is missing. Any specific reason why it was left out? Would be great to get it back in.

**Comment by tas50** [comment]
The timing property was available because the site resource wasnt' actually a resource but a definition. A definition just shoves a few resources into the middle of a chef run and works sort of like a macro. Since the new resources are within the chef run you have the ability to define restart timing as immediate or at the end of the chef run. We're using proper resources now, which have a lot of advantages, but they run in their own resource context instead of the main chef run. Since we're not in the main chef run there's no ability to delay the restart until the end of the chef run. The feature just doesn't make sense at this point due to the way custom resources work.
